### ISSUE TITLE
project has confusing name

### ISSUE THREAD

**Issue by conradsnicta** [pachadotdev/cpp11armadillo#3]
@pachadotdev It's good to see development of various R interfaces to Armadillo.

However, the name of this project is *confusing*, as it clashes with the official Armadillo project that is hosted at https://arma.sourceforge.net

The project in this repo is an R interface to Armadillo, and the project's name should reflect that to avoid user confusion with the official Armadillo library.

As an example, an existing R interface to Armadillo is called RcppArmadillo at https://github.com/RcppCore/RcppArmadillo/  
It's clear that it's related to Armadillo, but it has a unique name to avoid confusion.

Suggest that the project in this repo be renamed to something like PachaArma, or PachaArmadillo, etc.

cc @rcurtin @eddelbuettel

**Comment by pachadotdev** [comment]
> @pachadotdev It's good to see development of various R interfaces to Armadillo.
> 
> However, the name of this project is _confusing_, as it clashes with the official Armadillo project that is hosted at https://arma.sourceforge.net
> 
> The project in this repo is an R interface to Armadillo, and the project's name should reflect that to avoid user confusion with the official Armadillo library.
> 
> As an example, an existing R interface to Armadillo is called RcppArmadillo at https://github.com/RcppCore/RcppArmadillo/ It's clear that it's related to Armadillo, but it has a unique name to avoid confusion.
> 
> Suggest that the project in this repo be renamed to something like PachaArma, or PachaArmadillo, etc.
> 
> cc @rcurtin @eddelbuettel

thanks!
ok, I can rename to cpp11armadillo

**Comment by pachadotdev** [comment]
@conradsnicta renamed in [5389920](https://github.com/pachadotdev/cpp11armadillo/commit/5389920401ff4a311d5b8edf62bf6fc8be0a3c74)

I shall email CRAN now.
