### ISSUE TITLE
migrate from testthat to tinytest?

### ISSUE THREAD

**Issue by reikoch** [pachadotdev/cpp11armadillo#5]
I would like to raise attention to tinytest as a no-dependencies replacement for testthat, see for instance https://www.r-bloggers.com/2022/01/reduce-dependency-hell-from-testthat-to-tinytest/. Here it would have the additional benefit that the well developed test suite from Rcpparmadillo could be used.

What do you think?

**Comment by pachadotdev** [comment]
> I would like to raise attention to tinytest as a no-dependencies replacement for testthat, see for instance https://www.r-bloggers.com/2022/01/reduce-dependency-hell-from-testthat-to-tinytest/. Here it would have the additional benefit that the well developed test suite from Rcpparmadillo could be used.
> 
> What do you think?

Yes and no.

Yes, it is a good idea to use tinytest,

No, I will not use parts of Rcpparmadillo. It is a package released under GPL-3, and cpp11armadillo uses the Apache License 2.0, meaning that I would need to re-license everything as GPL-3 and face a lot of legal shenanigans at UofT.

**Comment by pachadotdev** [comment]
hi @reikoch 
what do you think of this?
https://github.com/pachadotdev/cpp11armadillo/commit/92b8f2d0ba0ba7b4cf00f9b3ca70cb2a29416f00

there is only one test I could not port https://github.com/pachadotdev/cpp11armadillo/commit/92b8f2d0ba0ba7b4cf00f9b3ca70cb2a29416f00#diff-ec401e0acfc9b8e514ab3d78a6c3fdaf6f5b48d4822bb5cea1a60a4be9efb1dbL2

**Comment by reikoch** [comment]
Oh yes, stay away from legal troubles!
Your conversion to tinytest has progressed well, let me look at it in detail.

**Comment by reikoch** [comment]
On my mac m2, running R 4.4.1 all tinytest tests work fine (6 in cpp11armadillo, 40 in cpp11armadillotest).

Which test did not port?

**Comment by pachadotdev** [comment]
> On my mac m2, running R 4.4.1 all tinytest tests work fine (6 in cpp11armadillo, 40 in cpp11armadillotest).
> 
> Which test did not port?

this one https://github.com/pachadotdev/cpp11armadillo/blob/main/tests/testthat/test-vendor.R#L2

and this ignores all the tests inside cpp11armadillotest

is there any reason to use tinytest?

**Comment by reikoch** [comment]
tinytest is tiny - and here it seems you need a bigger machinery like testthat. At least I cannot easily port function mocking and avoid bad side effects :-(

**Comment by pachadotdev** [comment]
> tinytest is tiny - and here it seems you need a bigger machinery like testthat. At least I cannot easily port function mocking and avoid bad side effects :-(

same here :(
