### ISSUE TITLE
Count of RcppArmadillo packages is off by a factor of thirty

### ISSUE THREAD

**Issue by eddelbuettel** [pachadotdev/cpp11armadillo#8]
> [RcppArmadillo](https://cran.r-project.org/web/packages/RcppArmadillo/) is a popular R package used by over 40 CRAN packages as of 2024-12-13.

Please see eg this [skeet](https://bsky.app/profile/eddelbuettel.com/post/3ld2nhsrgac2g), I included its (embedded in the ALT text) code here:

```r
> db <- tools::CRAN_package_db()
> (n_arma <- length(tools::package_dependencies("RcppArmadillo", reverse=TRUE, db=db)[[1]]))  
[1] 1200
> n_arma/nrow(db) * 100
[1] 5.5008
> 
```

You are off by a factor of 1200 / 40 = 30 which outside most common margins of error and I would appreciate it if you could correct it.  There are other errors in the README but I leave you to those -- the miscount is a little more serious.

**Comment by pachadotdev** [comment]
> > [RcppArmadillo](https://cran.r-project.org/web/packages/RcppArmadillo/) is a popular R package used by over 40 CRAN packages as of 2024-12-13.
> 
> Please see eg this [skeet](https://bsky.app/profile/eddelbuettel.com/post/3ld2nhsrgac2g), I included its (embedded in the ALT text) code here:
> 
> ```r
> > db <- tools::CRAN_package_db()
> > (n_arma <- length(tools::package_dependencies("RcppArmadillo", reverse=TRUE, db=db)[[1]]))  
> [1] 1200
> > n_arma/nrow(db) * 100
> [1] 5.5008
> > 
> ```
> 
> You are off by a factor of 1200 / 40 = 30 which outside most common margins of error and I would appreciate it if you could correct it. There are other errors in the README but I leave you to those -- the miscount is a little more serious.

Thanks. I appreciate this.

I only counted _Reverse imports_ and forgot to sum _Reverse linking_.
